type = {
    TYPE_NUMBER: 'TYPE_NUMBER',
    TYPE_LEFT_BRACKET: 'TYPE_LEFT_BRACKET',
    TYPE_RIGHT_BRACKET: 'TYPE_RIGHT_BRACKET',
    TYPE_OPERATION_ADD: 'TYPE_OPERATION_ADD',
    TYPE_OPERATION_SUB: 'TYPE_OPERATION_SUB',
    TYPE_OPERATION_MUL: 'TYPE_OPERATION_MUL',
    TYPE_OPERATION_DIV: 'TYPE_OPERATION_DIV',
}
module.exports = type


